name: Flight Data
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Fetch data
      uses: githubocto/flat-action@v1
      with:
        sql_connstring: ${{ secrets.CONNSTRING }}
        sql_queryfile: query.sql
        sql_format: csv
    - name: Commit and push if changed
      run: |-
        git config user.name "Flat"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
