name: Flight Data
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Fetch data
      uses: githubocto/flat-action@v1
      with:
        sql_connstring: ${{ secrets.CONNSTRING }}
        sql_queryfile: query.sql
        sql_format: csv
